#!/bin/sh /etc/rc.common
# authors: 	Wyliodrin


export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/opt/usr/bin:/opt/bin:/opt/usr/avr/bin
export NODEJS=/opt/usr/bin/node
export LD_LIBRARY_PATH=/opt/usr/lib
export NPM=/opt/usr/bin/npm
export NODE_PATH=/usr/lib/node_modules:/opt/usr/lib/node_modules:$NODE_PATH

START=99

start () {
  
    if [ -x $NODEJS ] && [ -e /wyliodrin/wyliodrin-app-server/startup.js ]
      
	then
	      cd /wyliodrin/wyliodrin-app-server	
	      $NODEJS --stack_size=1024 --max_old_space_size=20 --max_new_space_size=2048 --max_executable_size=5 \
		  --gc_global --gc_interval=100 startup.js & > /dev/null 2>&1
	  
      fi

}

stop () {

      kill -9 `ps www | grep wyliodrin-app-server | grep -v grep | awk {'print $1'}` > /dev/null 2>&1
      
}
